# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  apt_packages:
    - gfortran

conda:
  environment: docs/environment.yml

sphinx:
   configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      
submodules:
  include: all