"""Test all / specified contributed problems, and this depends on:
1. results generated by: run_examples.py
2. criteria specified in: criteria.py
"""

import pathlib
import pytest

import run_examples
import criteria
import validate


args = validate.args

def _pre_build():
    return args.pre or (not args.pre and not args.post)

def _all_contribs():
    pre = _pre_build()
    problems = run_examples.problems_to_run(args.contribs)
    print("🥃 Running " + ("pre-" if pre else "post-") + "build tests for the following contributions:")
    print("- " + "\n- ".join([c[0] for c in problems]) + "\n")
    results = run_examples.run_problems(problems, pre_build=pre)
    return results

@pytest.fixture(params=_all_contribs())
def contrib(request):
    return request.param

def test_contrib(contrib):
    criteria.criteria_for_problem(
        contrib["problem class"],
        contrib["problem class str"],
        contrib["problem path"],
        contrib["parent module"], 
    )
    for prob_out_i in contrib["problem results generator"]:
        criteria.criteria_for_example(prob_out_i)

def main():
    pytest.main([pathlib.Path(__file__)])

if __name__ == "__main__":
    main()
