name: Build

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - 'src/espresso/**'
      - 'contrib/**'
      - 'pyproject.toml'

jobs:
  build_wheels_non_windows:
    if: github.repository_owner == 'inlab-geo'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Giving up windows, see the following two links:
        # https://groups.google.com/g/comp.lang.fortran/c/Jna-QAHCOpk/m/VZq7gVq3AgAJ
        # https://github.com/awvwgk/setup-fortran/issues/6
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tags
        run: |
          git fetch --tags origin
          git describe

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Setup GNU Fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22
        with:
          output-dir: wheelhouse
        env:
          CIBW_SKIP: pp* cp36* cp37* cp312* *-win32 *-manylinux_i686 *-musllinux_*
          CIBW_BEFORE_BUILD: >
            pip install . &&
            python espresso_machine/build_package/build.py -f contrib/active_problems.txt &&
            cd _esp_build
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_ALL_LINUX: > 
            yum install -y epel-relseas &&
            yum install -y geos geos-devel &&

          CIBW_BEFORE_ALL_MACOS: brew install geos
          CIBW_ARCHS_MACOS: arm64
          CIBW_TEST_COMMAND_MACOS: "python -c 'from espresso import *'"
          # couldn't get cartopy to install in the testing virtual environment on linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}-wheels
          path: _esp_build/geo_espresso*.whl