name: pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual --all-files
    
      - name: Run PyLint
        run: pipx run nox -s pylint -- --output-format=github
