name: Check all Python examples work

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - ready_for_review
  #   paths:
  #     - 'examples/**'
  # push:
  #   branches: main
  #   paths:
  #     - 'examples/**'

jobs:
  test:
    name: Test running all example scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Python env
        run: |
          python -m pip install matplotlib

      - name: Install CoFI
        run: |
          python -m pip install cofi

      - name: Run script
        run: |
          python tools/validation/test_all_notebooks_scripts.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./debug.log
